plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'helios'

include(
    "helios-common",
    "helios-engine",
    "helios-storage",
    "helios-proto",
    "helios-frontend",
    "helios-sdk",
    "helios-worker",
    "helios-testing",
    "helios-samples",
    "helios-server"
)